### ISSUE TITLE
Make verbose logging optional

### ISSUE THREAD

**Issue by Radiergummi** [cagataygurturk/docker-ssh-tunnel#3]
This image is super useful, but I find the massive amount of logs generated by ssh due to the `-vv` parameter to be quite annoying. Would it be possible to provide an environment variable to enable debugging? Something like `DEBUG=1` to enable adding the parameter, or maybe just `SSH_PARAMS=-vv` to pass custom parameters to the command.

**Comment by Radiergummi** [comment]
Hah, haven't even seen there's a PR open for this already at #2. Would be awesome if you could merge it 😊

**Comment by cagataygurturk** [comment]
Fixed by #2
